### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by changchanghwang** [TeamOfAnts/discord-shuffle-bot#1]
- [ ] 좀더 클리어하게 만들기
  - ui적인 요소? 
- [ ] 서버 어떻게 할지 정하기
  - 네이버 크레딧 준걸 써볼까
- [ ] 이전 팀 기억해서 shuffle 로직 고도화
